// <auto-generated />
namespace CB180936_AR172433_DESAFIO01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Transacciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Transacciones));
        
        string IMigrationMetadata.Id
        {
            get { return "202109162318264_Transacciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
